#!/bin/sh

help="Welcome to gnome-debloater, 
this program is used to debloat the 
gnome in different debian installs.

d(x) refers to different debian editions.

EX: dt is debian testing. (run this script as root)

h < displays the help message
ds < debloats debian bullseye
dt < debloats debian bookworm
dus < debloats debian sid"

case $1 in
        h | help)
	        echo "$help"
		;;

	ds | debian-stable)
		apt-get purge gnome-games gnome-sound-recorder im-config evolution synaptic shotwell gnome-todo transmission-gtk gnome-characters gnome-music malcontent file-roller gnome-documents && apt-get autoremove && apt-get upgrade && apt-get update
		;;

	dt | debian-testing)
		apt-get purge gnome-games gnome-sound-recorder im-config evolution synaptic shotwell gnome-todo transmission-gtk gnome-characters gnome-music malcontent file-roller gnome-documents seahorse && apt-get autoremove && apt-get install gnome-connections power-profiles-daemon && apt-get upgrade && apt-get update
		;;
       
	dus | debian-unstable)
		apt-get purge gnome-games gnome-sound-recorder im-config evolution synaptic shotwell gnome-todo transmission-gtk gnome-characters gnome-music malcontent file-roller gnome-documents seahorse && apt-get autoremove && apt-get install gnome-connections power-profiles-daemon && apt-get upgrade && apt-get update
		;;
     
	*)
		echo "$help"
		;;

esac
